### ISSUE TITLE
Where is the version text number stored ?

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Radioddity_GD-77#27]
I wanted to change the version number, so that people could check what version of patched firmware they are running , but I have not managed to find where it’s stored.

The value displays as “v3.01.08”, but I can’t find that string in the ROM.

I also looked for a sprintf string e.g. “v%” ... but could not find that either.

I tried looking in the menu display system, but it’s hard to see what’s going on, because I think it uses function pointers, and Ghidra can’t find the linkages, and the decompilations are not much help either.

I may have to resort to putting a breakpoint in sprintf or printf to see if I can catch when it’s writing the number to the screen and trace back from there

**Comment by forkoz** [comment]
so far the only place I found is in the BL: 39AD0, i'll keep looking

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Comment by forkoz** [comment]
says something like  "MD-760P" "V318".  Its put into somewhere in ram. Not in the BL, aparently I can't count.

**Comment by rogerclarkmelbourne** [comment]
not triggering :-(

**Comment by forkoz** [comment]
heh, change to 319 and see what happens, it could also be in the flash memory, written during update

**Comment by rogerclarkmelbourne** [comment]
I checked and I'd forgotten I tried patching that ages ago.I already changed it to C001 and it made no difference.

In fact the firmware that I am using has that string as C001

**Comment by rogerclarkmelbourne** [comment]
0xf9f8 seems to load the menu item(s)

**Comment by rogerclarkmelbourne** [comment]
Strange..

The read watches seem to be tiggering now...

0x39Ac8 by a read from instruction address  0x2d102, which is possibly called from 0x3adfc (though the stack trace is unreliable in GDB)

**Comment by forkoz** [comment]
0xf9f8 looks like 0x2d0f0

This is what that line is for me: for ( i = *(_DWORD *)a2; !((i - 0x1010101) & ~i & 0x80808080); i = v5 )

**Comment by rogerclarkmelbourne** [comment]
umm

Some sort of obfuscation ?

**Comment by forkoz** [comment]
i was more thinking binary or some bit operation.

**Comment by rogerclarkmelbourne** [comment]
Ah OK.

There is some code in the Private Call handling that looks for a newline and removes it I think.

I agree, its possibly a fast search algorithm.

**Comment by forkoz** [comment]
does it search or align the bytes. its going through chinese characters and the menu at the least.

**Comment by rogerclarkmelbourne** [comment]
OK.
I just dumped the memory when the version was being displayed, and it looks like it builds a single string with all the "Info" in it
Note. these are addresses from the base of RAM, so you need to add 0x1fff0000

```
Offset(h) 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F

0000C320  16 00 1A 00 38 00 15 00 00 43 50 53 2D 56 65 72  ....8....CPS-Ver
0000C330  73 69 6F 6E 3A 00 18 00 38 00 15 00 00 32 31 3A  sion:...8....21:
0000C340  35 30 00 00 38 00 15 00 00 76 33 2E 31 2E 43 00  50..8....v3.1.C.
0000C350  44 65 76 2E 20 49 6E 66 6F 00 1B 00 38 00 15 00  Dev. Info...8...
0000C360  00 48 2D 56 65 72 73 69 6F 6E 3A 00 38 00 15 00  .H-Version:.8...
0000C370  00 56 33 2E 30 31 2E 30 38 00 1D 00 38 00 15 00  .V3.01.08...8...
0000C380  00 32 30 31 39 2E 30 33 2E 33 31 00 38 00 15 00  .2019.03.31.8...
0000C390  00 53 6F 66 74 2D 56 65 72 73 69 6F 6E 3A 00 00  .Soft-Version:..
0000C3A0  38 00 15 00 00 44 53 50 2D 56 65 72 73 69 6F 6E  8....DSP-Version
0000C3B0  3A 00 00 00 38 00 15 00 00 48 52 43 36 30 30 30  :...8....HRC6000
0000C3C0  20 56 31 2E 32 00 1F 00 38 00 15 00 00 50 72 6F   V1.2...8....Pro
0000C3D0  67 72 61 6D 20 54 69 6D 65 3A 00 00 08 00 17 00  gram Time:......
```

**Comment by rogerclarkmelbourne** [comment]
0x3a042 is also part of the menu system, possibly something to do with the display of the letters in the menu as it gets called a lot when displaying the menu's. 

It also gets called however to display the Zone List, but I guess thats a sub part of the menu's really

**Comment by forkoz** [comment]
So funny about that ram stuff. In your dump it has DHS AU at that spot and a lot of zeros. Maybe  this is a general screen/menu buffer.

**Comment by rogerclarkmelbourne** [comment]
Yep. I think thats the case. 
I was grasping at straws to see if I could put a watch on the address and see which function used the same block of memory, which was how I found function 0x3a042

**Comment by rogerclarkmelbourne** [comment]
![image](https://user-images.githubusercontent.com/6146984/55297063-c84a6d00-546d-11e9-851a-f5538f98e41e.png)

**Comment by forkoz** [comment]
On my end, nothing appears to link there directly. There is data in the ram but no xrefs.

**Comment by rogerclarkmelbourne** [comment]
Umm.
The linkage must be via the menu definition structure.

**Comment by forkoz** [comment]
It usually finds that.. but who knows.  Generally I get at least the first dword/byte/etc when a function loads it into memory.

**Comment by rogerclarkmelbourne** [comment]
I found that the version string at 0x39ac8 is used by the CPS USB handling


I was looking for why the radio reboots after a codeplug upload (because there is no need to do that if its a DMR ID upload), and looking for the end string "END" that the CPS sends

I found the CPS USB handler    CPS_USB_00039856

And it also references the version string, at 0x39ac8

**Comment by forkoz** [comment]
So version must be in the flash

**Comment by forkoz** [comment]
So I found a version comparing function: CompareVersion_397B8, looks like its written into 0xb8 in the eeprom if it doesn't match. If you want to alter the number I think this is where to do it.

```
int *CompareVersion_397B8()
{
  int *v0; // r3@1
  int *v1; // r3@3
  int *result; // r0@3
  char Version_string; // [sp+0h] [bp-18h]@1
  char v4; // [sp+1h] [bp-17h]@1
  char v5; // [sp+2h] [bp-16h]@1
  char v6; // [sp+3h] [bp-15h]@1
  char v7; // [sp+4h] [bp-14h]@1
  char v8; // [sp+5h] [bp-13h]@1
  char v9; // [sp+6h] [bp-12h]@1
  char v10; // [sp+7h] [bp-11h]@1
  unsigned __int8 Buffer; // [sp+8h] [bp-10h]@1
  unsigned __int8 v12; // [sp+9h] [bp-Fh]@4
  unsigned __int8 v13; // [sp+Ah] [bp-Eh]@5
  unsigned __int8 v14; // [sp+Bh] [bp-Dh]@6

  spi_flash_read(0xB8u, (int)&Buffer, 8);
  Version_string = 'V';
  v4 = '3';
  v5 = '.';
  v6 = '0';
  v7 = '1';
  v8 = '.';
  v9 = '0';
  v10 = '8';
  if ( !compare_1F48E((int)&Buffer, 8, (int)&Version_string, 8) )
    eeprom_write_15DDC(0xB8u, (int)&Version_string, 8, v0);
  spi_flash_read(4u, (int)&Buffer, 8);
  result = (int *)Buffer;
  if ( Buffer == 255 && v12 == 255 && v13 == 255 && v14 == 255
    || Buffer == 'T'
    && (result = (int *)v12, v12 == 'E')
    && (result = (int *)v13, v13 == 'M')
    && (result = (int *)v14, v14 == 'P') )
  {
    result = eeprom_write_15DDC(4u, (int)&Version_string, 8, v1);
  }
  return result;
}
```

**Comment by rogerclarkmelbourne** [comment]
Thanks

I thought that the version number must be encoded somewhere in the header of the SGL, and then written into the EEPROM by the bootloader 

But it would be better if it was in the firmware file, so perhaps I can change that function if it reads the EEPROM , and used a constant string instead

I will put a breakpoint in that code and see what it’s doing

**Comment by forkoz** [comment]
There are 2 version strings. One at the head of the file at 0x4 and the other at 0xB8. It simply reads the eeprom and if its not matching writes the string. It only writes 0x4 if you just did factory reset which is what writes TEMP in that string. I confirmed this by that patch where I read from 0x0

**Comment by rogerclarkmelbourne** [comment]
So can I modify the header file somehow ?

I tried decoding by modifying Kai’ “stripper” function, but didn’t notice anthing which is obviously the version e.g. v3.01.08

**Comment by forkoz** [comment]
You don't need to do anything with the header. Its just read from codeplug/eeprom. But if you changed it in the codeplug this function would overwrite it.


So just patch the version listed and make "temp" a second copy of the version string.

Read from 0x0:

![gd77](https://user-images.githubusercontent.com/12354546/55913613-a5753280-5baa-11e9-89b9-ecb2ba5abb3f.png)

**Comment by rogerclarkmelbourne** [comment]
So the easiest way to change the version is just to change the stuff which Ghidra decompiles as

```
  local_18 = 0x56;
  local_17 = 0x33;
  local_16 = 0x2e;
  local_15 = 0x30;
  local_14 = 0x31;
  local_13 = 0x2e;
  local_12 = 0x30;
  local_11 = 0x38;
```

**Comment by rogerclarkmelbourne** [comment]
I'll change it to C.0.00.01

**Comment by jmspswny** [comment]
no 42?

**Comment by rogerclarkmelbourne** [comment]
HHGTTG?

**Comment by jmspswny** [comment]
Don't Panic.

**Comment by rogerclarkmelbourne** [comment]
LOL.
I'm showing my age;-)

OK. So how about C0.00.42

**Comment by jmspswny** [comment]
gotta start somewhere.  and that's as good a place as any.

**Comment by rogerclarkmelbourne** [comment]
True

**Comment by forkoz** [comment]
heh, I was just going to do 31337 or something. But I think you need both places, not sure which one goes in the menu. Seems to be returning the one at 0x4 so I'd think that one.

**Comment by rogerclarkmelbourne** [comment]
I'll patch it now and see what happens

**Comment by rogerclarkmelbourne** [comment]
![image](https://user-images.githubusercontent.com/6146984/55916201-06464e80-5c2f-11e9-8f59-430039aea580.png)

**Comment by rogerclarkmelbourne** [comment]
PS. I got plastic swarf in the display when I drilled the hole for the swd wires, but its a pain to take it apart again :-(

**Comment by jmspswny** [comment]
SHIP IT!

**Comment by rogerclarkmelbourne** [comment]
I may also change "Soft-Version" string to "Firmware"

**Comment by forkoz** [comment]
Did you just change the 1 or both?

**Comment by rogerclarkmelbourne** [comment]
Just the compare function

**Comment by rogerclarkmelbourne** [comment]
[GD-77_V3.1.8_0CD1_077001.dec.patch_version_num_C0.00.42_397B8.zip](https://github.com/rogerclarkmelbourne/Radioddity_GD-77/files/3066100/GD-77_V3.1.8_0CD1_077001.dec.patch_version_num_C0.00.42_397B8.zip)

**Comment by forkoz** [comment]
It shows up in CPS too :)
![versions](https://user-images.githubusercontent.com/12354546/55920839-e7f53a00-5bbf-11e9-84ec-472ad44edec8.png)

**Comment by rogerclarkmelbourne** [comment]
lol

**Comment by rogerclarkmelbourne** [comment]
Solved I think...

**Comment by forkoz** [comment]
We should put it in the patches.

**Comment by rogerclarkmelbourne** [comment]
Yes. Good idea or the wiki or both ;-)
