### ISSUE TITLE
Bug list firmware

### ISSUE THREAD

**Issue by sp2ong** [rogerclarkmelbourne/Radioddity_GD-77#3]
Hi,
According to the list of bugs GD-77:

https://github.com/rogerclarkmelbourne/Radioddity_GD-77/wiki/Firmware-bugs

what about bug described 

https://www.rogerclark.net/radioddity-gd-77-firmware-3-1-8-dmr-display-bug/

which in 3.1.8 is annoying using every day GD-77. Is it fixed in v3.2 1?

**Comment by rogerclarkmelbourne** [comment]
See my reply to on my blog,, but AFIK no bugs were fixed in 3.2.1

See

https://github.com/rogerclarkmelbourne/Radioddity_GD-77/blob/master/firmware/UpdateDiary.txt

**Comment by rogerclarkmelbourne** [comment]
PS. Can you help with the reverse engineering of the firmware.

Using Ghidra is very interesting.

You don't need to open your radio etc, just looking a the Assembly and C code could be useful

**Comment by sp2ong** [comment]
Roger,

I thought that this bug will be added on the list:
https://www.rogerclark.net/radioddity-gd-77-firmware-3-1-8-dmr-display-bug/

> See my reply to on my blog,, but AFIK no bugs were fixed in 3.2.1
> 
> See
> 
> https://github.com/rogerclarkmelbourne/Radioddity_GD-77/blob/master/firmware/UpdateDiary.txt

**Comment by sp2ong** [comment]
Ok, I will try to see, but my programming skills are not at a high level 

> PS. Can you help with the reverse engineering of the firmware.
> 
> Using Ghidra is very interesting.
> 
> You don't need to open your radio etc, just looking a the Assembly and C code could be useful

**Comment by rogerclarkmelbourne** [comment]
Thanks

I'll try to document, what to do so that the ROM and RAM are correctly imported into Ghidra.
