### ISSUE TITLE
How to find functions and symbols in new firmware versions

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Radioddity_GD-77#46]
With the release of firmware 3.2.2 and possibly more updates in the future, we probably need a way to find the matching functions in the new firmware versions, using the known function addresses in firmware 3.1.8

Looking at this video presentation by Travis Goodspeed, he explains how they find new symbols

https://youtu.be/GX8-K4TssjY?t=2165

Specifically, I tracked down the code which they use, which is an updated version of the code he discusses in the video

https://github.com/travisgoodspeed/md380tools/blob/master/symbols/symgrate.c

I have various C compilers installed on my PC, including Visual C++ and Code::Blocks
Or I may just compile it on Linux and use his Makefile

There are "annotation" files which seem to contain lists of symbols, but there are multiple annotation files, which probably get merged together to make a single symbols file

There seem to be some scripts for converting from "symbol" files to Ghidra and from 
https://github.com/travisgoodspeed/md380tools/blob/master/annotations/s13.020/flash.r

Looking at the symbol conversion files 

https://github.com/travisgoodspeed/md380tools/blob/master/symbols/symbols2idapy.py

https://github.com/travisgoodspeed/md380tools/blob/master/symbols/symbols2ghidra.py

Both scripts have this comment

> ...parser for converting symbol files from the # GNU LD format used in the MD380Tools project

So I presume that the file compare utility expects the symbols file to be in GNU LD format :-(

Hence the options would be to write some utility to convert from CSV from Ghidra to GNU LD and then run the compare utility (unmodified), or...
Modify the compare utility..

Since either way requires work, I think its better to modify the compare utility to read CSV

**Comment by forkoz** [comment]
The flash.r stuff is for radare.

**Comment by rogerclarkmelbourne** [comment]
Superseded by the OpenGD77 firmware
