### ISSUE TITLE
Inverted colour display

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/Radioddity_GD-77#47]
BTW

It should be possible to partially replicate the inverted display model of the GD-77, because the UC1701 display controller has an inverted mode.

The normal setup code is 0xA4 and the command to set inverted colour mode is 0xA7.

I found some code that looks a bit like its the display initialisation in FUN_0002f3ec
but at sets the mode to A4 and then A7. which doesn't make any sense if its the display init

FYI.

The display init in Kai's code is

```
void UC1701_begin(bool isInverted)
{
	UC1701_column = 0;
	UC1701_line = 0;

	GPIO_PinWrite(GPIO_Display_CS, Pin_Display_CS, 0);// Enable CS permanently

    // Set the LCD parameters...
	UC1701_setCommandMode(true);
	UC1701_transfer(0xE2); // System Reset
	UC1701_transfer(0x2F); // Voltage Follower On
	UC1701_transfer(0x81); // Set Electronic Volume = 15
	UC1701_transfer(0x0E); //
	UC1701_transfer(0xA2); // Set Bias = 1/9
	UC1701_transfer(0xA1); // A0 Set SEG Direction
	UC1701_transfer(0xC0); // Set COM Direction
	if (isInverted)
	{
		UC1701_transfer(0xA7); // Black background, white pixels
	}
	else
	{
		UC1701_transfer(0xA4); // White background, black pixels
	}
    UC1701_clear();
    UC1701_setCommandMode(true);
    UC1701_transfer(0xAF); // Set Display Enable

}

```

So there are definitely similarities between that function and Kai's code

I guess one way to know if that function is the display init, is patch so it doesn't get called, and see what happens !

**Comment by forkoz** [comment]
that UC1701_transfer is how it draws. so for sure that's the init.

**Comment by forkoz** [comment]
change it to A4 instead... but still has the stupid outline of blank vs black. Wish I knew where it drew that outline so it could be like the DM1801. Plus I have a row of dead pixels so this mod wouldn't really do any good for me.

![inverted](https://user-images.githubusercontent.com/12354546/58253172-71566b00-7d2d-11e9-9644-271846e34805.png)

**Comment by rogerclarkmelbourne** [comment]
Yep.. it’s not completely inverted all the way to the edge.

The official inverted version uses a different LCD panel.

I think there may also be some bugs in the display code which may not clear the whole screen, and I have noticed some unset pixels when I move icons etc, which indicate something is wrong in their display library.

I have just finished writing a display library for Kai’s firmware, and it has highlighted some interesting things..

The display controller is 132x65 pixels but the physical LCD is only 128 x 64.
Hence there are 4 bytes at the start of each horizontal block, which can be written to , but are not displayed in the LCD.

I have a feeling that the official firmware treats each line as 128 pixels, and but sets the minimum x value they use to 4.

Because now that I moved the call icon and use all 15 chars for the callsign and name, I sometimes end up with some pixels rendered on the right which appear to be beyond the right side of the display

This would partially explain why you get that annoying line around the edge.

In my code I still use 128 pixels per line, but I used an offscreen buffer, and send it to the display, with a 4 pixel x offset

**Comment by forkoz** [comment]
Its the same on the DM1801 and the screen is not perfectly aligned. Are we sure they use a different panel and not just extend the black border around the LCD furthern in? I almost bought a dark screen GD77 when I was looking (in fact it was supposed to be but the guy lied)... I'm kinda glad I didn't as the black isn't rich enough.

Perhaps there is a way to fill the rest of the screen with black instead of nothing.

**Comment by rogerclarkmelbourne** [comment]
They may be using a slightly different LCD panel in the DM-1801, the radio is not quite the same.

Radioddity told me its a clone and does not come from the TYT factory, but its really hard to know precisely the supply chain

I put a mode switch for this into Kais firmware, but I also need to change the backlight to be PWM, so that the brightness can be turned down, especially when in inverse video, as I think that would improve the clarity.

**Comment by rogerclarkmelbourne** [comment]
Another thing you can try is changing the contrast value, aka "Electronic volume"

Its set to 0x0E, but I've experimented with a few values and 0x14 or perhaps 0x16 gives more contrast, and makes the black look blacker.

I'm not sure if this would eventually cause burn-in onto the LCD panel, but its definitely easier to read if the you increase the contrast

BTW. According to the data sheet, the default value is 0x20, but I tried that value and the background pixels start to turn grey, so the number is bit too high for the LCD panel in the GD-77, but the value Radiodity use, (0x0E) is too low in my opinion.

Looking at some other libraries that use the same controller, they use wildly different values. One uses 0x40, which would make the LCD totally black on the GD77.

**Comment by forkoz** [comment]
Wonder if there is a way to reduce the brightness via software on the stock fw end too. When it sets the top bar to black its all white too and that looks a bit funny.

**Comment by rogerclarkmelbourne** [comment]
I doubt if the GPIO pin which controls the backlight is configured for use with PWM.

I'm not sure how to go about doing this on the MK22, I'd need to find and example in the NXP MK22 SDK.

We could probably patch something in to the code to configure and then use PWM but it would mean changing the initial pin config setup and also anywhere the code turned the backlight pin On or Off

**Comment by forkoz** [comment]
Well they used a standard library, it could be pwm and set to 255. Finding it is another story. BTW 0x10 is a nice value. 20 is too much and 8 puts ghosts in the screen. Up to 0x15 is ok but I like 10 for some reason.

**Comment by rogerclarkmelbourne** [comment]
Probably each radio will have an optimum value.

Mine is Ok , up to about 0x18, but I will probably end up using 0x12 or 0x14

I will need to write a contrast control screen for Kai’s firmware, and probably be able to change the setting via the CPS

**Comment by forkoz** [comment]
heh, I need to find a replacement LCD for my gd77 and maybe switch the one in the DM1801 if I want to use this. 1801 is too blue on all settings but the GD77 at least looks black.

**Comment by rogerclarkmelbourne** [comment]
Superseded by the OpenGD77
