### ISSUE TITLE
2 major bugs when using DCDM in the DM-1801

### ISSUE THREAD

**Issue by gman1974** [rogerclarkmelbourne/Radioddity_GD-77#49]
I am writing these here in case anyone knows a way to fix them.
Bug #1 
When DCDM is enabled in any given channel, the Timing Leader which sent its timing sync TX last won't exit the next group call. Repro steps: Have 3 radios on a channel, all three with DCDM enabled create two RX group lists on all three radios: AAA and BBB. After the timing leader has sent its TX packets, pick one of the other two radios that didn't send anything and press the PTT to make a group call in AAA. When the PTT is released, the radio that sent the TX sync packets will never leave the group call, thus making it impossible to hear any other group calls.
Bug #2
When DCDM is enabled and Allow Criteria for a channel is set to Channel Free, sometimes, when the timing leader sends its sync TX packets, ALL other radios in the channel with DCDM enabled the RX light will be solid green and the radio will be unable to transmit until the channel is changed (or powered off). When you try to press the PTT you get a message stating TX: CC amount limit exceeded. (or something like that)

Pretty major bugs if you ask me, one of the big things in DMR is the DCDM feature... lets see if Baofeng fixes that, or if someone knows how to fix that. 

G.

**Comment by rogerclarkmelbourne** [comment]
This repo is primarily for the GD-77. I will close this as there were no responses
