### ISSUE TITLE
GD77 vs 1808

### ISSUE THREAD

**Issue by gman1974** [rogerclarkmelbourne/Radioddity_GD-77#50]
I just got a couple of GD77s today. I proceeded to bench the RF performance and both radios have about equal performance in VHF analog, I am not sure if digital is any better, TBH, but the GD77 radio has a very low sensitivity receiver just like the 1801. 

Rogerclark, you mentioned that you were able to flash the 1801 firmware into the GD77, is that correct? I might do that just to have all my radios using the same CPS...

Thanks.

**Comment by rogerclarkmelbourne** [comment]
See the data compiled by Jason VK7ZJA

http://members.optuszoo.com.au/jason.reilly1/GD77mods.htm

As far as I can see the GD-77 is not insensitive, but I guess it depends on what you compare it with.

**Comment by gman1974** [comment]
Very nice, thank you.

Well, yes, I totally agree, the and radio is not useless if that is what you think I meant to say... I own 12 of them, if that is of any indication; but then again, its just a tool, and every tool is useful for the right job; and for short range inexpensive intercoms these are very hard to beat. Sure, the XPR7550e will blow its doors off in pretty much every conceivable benchmark, except price...

I am also a bit curious as to what SINAD figures where those measurements taken, 12dB SINAD?, in my experience I've found a direct correlation between analog RX performance and digital RX performance. 

Regardless of the sensitivity, I am rather interested in trying the OpenGD77 firmware you wrote. How is the Tier 2 stuff coming along? 

At some point I also need to test the DCDM bug in these GD77s...

G.

**Comment by rogerclarkmelbourne** [comment]
Tier 2 (technically its called Tier 2 Passive), is sort of working, except I can't wake up the repeater, and also there is an intermittent audio buffering problem, and also some crash bugs.

I'm working on the wake-up system at the moment, but I keep uncovering other things I need to change in order to get the wake-up system working

**Comment by gman1974** [comment]
What language are you using to program these?

G.

**Comment by rogerclarkmelbourne** [comment]
C

(not C++)

**Comment by gman1974** [comment]
Just good old C; and any particular compiler? Turbo C? Watcom C? GCC?
CLANG? VCC?

**Comment by rogerclarkmelbourne** [comment]
It uses the NXP IDE, which uses GCC

**Comment by gman1974** [comment]
NXP IDE... good to know... 

BTW, I just verified that the DCDM bug is present on the latest GD77 firmware too. I am genuinely shocked that something as easy to repro as this bug has gone unnoticed for this long! My DMR Alinco MD5s and Anytone 878s work fairly well in DCDM mode. 

Thoughts?

G.

**Comment by rogerclarkmelbourne** [comment]
No idea.

I gave up on the official firmware months ago. Thats why I'm writing my own

**Comment by gman1974** [comment]
Kinda figured that, one doesn't go into writing a whole radio OS if they
can get what they need out of the one supplied.

So, what is exactly this issue you're trying to solve now?
