### ISSUE TITLE
DM-1801 Com issue

### ISSUE THREAD

**Issue by lwismer44** [rogerclarkmelbourne/Radioddity_GD-77#55]
Cannot communicate with DM-1801 radio even after buying a new FTDI real chip cable. One day it just stopped communicating with the PC. Other radios work, so i belive it to be the DM-1801 Itself, or the CPS. The CPS has no option to choose a COM port so i am wondering if anyone else has had this problem and has solved it.
![Annotation 2020-01-04 190852](https://user-images.githubusercontent.com/44852200/71773154-c003ee80-2f25-11ea-8d41-149e065737dd.png)

**Comment by rogerclarkmelbourne** [comment]
The DM-1801 doesn't have a chip in its cable.
