### ISSUE TITLE
cleanup of https://github.com/forkoz/GD-77

### ISSUE THREAD

**Issue by talentraspel** [rogerclarkmelbourne/Radioddity_GD-77#6]
done

**Comment by forkoz** [comment]
Frankly, they don't scare me. Considering tytera are selling a radio with an unlicensed solution, even more so. DVSI might be happy we are sticking it to them, imo. I can make it private for your sake if you wish.

**Comment by talentraspel** [comment]
Please do so, if possible. It's better overall for the open source hamradio DMR situation if we keep the roots as clean as possible. Thanks a lot.
